### ISSUE TITLE
frmPayrollLeave.aspx

### ISSUE THREAD

**Issue by ahmedra2fat** [TIT-eg/HR#115]
في شاشة الاجازات المدفوعة

عند تغيير قواعد الرواتب وصرف الاجازات من قواعد النظام في النظام الاصلي يحدث اختلاف في حسبة الاجازات من شاشتي التعديل واحتساب راتب اجازة بين النظام الجديد والنظام الاصلي
وايضا في هذه الحالة النظام الجديد لا يطبع تقارير الشاشتين
فيجب مطابقة النتائج بين النظامين في كل الحالات وايضا طباعة التقارير بصرف النظر عن التغيير اذا كانت الحسبة على 26 يوم او 0 ويعني انه حسب ايام الشهر او 30 يوم وايضا يوجد بعض العملاء يختلف لديهم حسبة الراتب الشهري عن حسبة راتب الاجازة فلابد مطابقة النتائج في كل هذه الحالات وكل هذا الاختلاف بالتأكيد موضح بالكود
![image](https://user-images.githubusercontent.com/71769652/103087416-77db5180-45f8-11eb-9dff-62256b818f46.png)
![image](https://user-images.githubusercontent.com/71769652/103087459-9e00f180-45f8-11eb-821b-292fd0280af4.png)

**Comment by Msamy1999** [comment]
يرجى توضيح مكان الصفحة

**Comment by ahmedra2fat** [comment]
frmPayrollLeave.aspx
شاشة صرف راتب الاجازة مقدم

**Comment by Msamy1999** [comment]
<img width="523" alt="Screenshot_26" src="https://user-images.githubusercontent.com/90830374/145713067-2d0a19b6-2911-4f09-9071-23a6d02cc420.png">
<img width="295" alt="Screenshot_27" src="https://user-images.githubusercontent.com/90830374/145713071-204b1e14-1a45-421c-8767-003c84a1a549.png">
<img width="545" alt="Screenshot_28" src="https://user-images.githubusercontent.com/90830374/145713072-f8ece0ad-854b-4bdd-82d6-875a7007eb35.png">
<img width="233" alt="Screenshot_29" src="https://user-images.githubusercontent.com/90830374/145713073-baaf7990-0991-40b2-93f7-b48a3cc63b10.png">

**Comment by Msamy1999** [comment]
جربت على كذا موظف و مفيش فرق في الارقام دلوقتي
لو في فرق عندك صور رقم الموظف و التاريخ الحطه

**Comment by ahmedra2fat** [comment]
تم
