### ISSUE TITLE
frmOverTimeAdd.aspx

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#128]
1- عند اضافة عمل اضافي جديد عند اختيار نوع العمل الاضافي النظام يجب ان يملا الحقول التالية:
* قيمة الساعة 
* تحسب الساعة ب
* القيمة الاجمالية

2- عند الضغط علي موافق النظام يعطيError

**Comment by ahmedra2fat** [comment]
تمام انا جربت عندي الحين بيحسب وبيحسب صح نفس النظام الاصلي
بس في شوية مشاكل
1 - في حالة الاضافة وبعد تعبئة البيانات والنظام طبعا بيحسب الحسبة صح ولكن لو غيرت عدد الساعات النظام في الحالة دي مابيغيرش حسبة القيمة الاجمالية والمفروض ان بمجرد اني اغير عدد الساعات النظام علطول يعدل حسبته

2- جزئية التأكد من الحد الاقصى لاتعمل
![image](https://user-images.githubusercontent.com/71769652/147940398-d4db1bfa-91f9-4f19-a4cb-32a53933854a.png)

3- في حالة التعديل على سجل عمل اضافي وعند تغيير عدد الساعات فالنظام بيحسب تمام ولكن بيزود عدد الارقام العشرية في خانة القيمة الاجمالية فياريت نخليها هما 3 ارقام عشرية فقط

4 - نوع الدفع استثنائي غير موجود
![image](https://user-images.githubusercontent.com/71769652/147940943-15902362-7fe4-4790-bd7e-bfa749092aca.png)
![image](https://user-images.githubusercontent.com/71769652/147940993-38cbd3a7-de0c-4397-af5c-409b05f1afc6.png)

**Comment by Msamy1999** [comment]
محتجين اخر كود عشان إستثنائي مش عندنا

**Comment by ahmedra2fat** [comment]
النقطة 2 ماتعملتش
2- جزئية التأكد من الحد الاقصى لاتعمل

النقطة 4 انا شيكت مع المهندس كمال عن الكود وتبين ان الكود اللي فيه النقطة دي مرسلة ليكم من شهر 05/2021 تقريبا فممكن تشيكو مع محمد قورين
4 - نوع الدفع استثنائي غير موجود



في بعض الموظفين بيختلف احتساب قيمة الساعة بين النظامين بفلس تقريبا المهم انه رقم تافه بس طبعا مع العدد بيفرق وكمان لازم يكون نفسة بالظبط فياريت تشيك عليها هل هي تقريب الكسور ولا غلط في الحسبة
![image](https://user-images.githubusercontent.com/71769652/150995027-082ab709-7e9f-4b48-acc1-4f8043d465b0.png)
![image](https://user-images.githubusercontent.com/71769652/150995177-68578470-c53d-41cf-a17d-9bc1551b1d8a.png)


زر تقرير مالوش لازمة الشاشة مابنطبعش منها تقرير
![image](https://user-images.githubusercontent.com/71769652/150995893-4abc1013-57d1-4043-9981-c7586906bd08.png)

النظام مابيحسبش للموظف رقم 11 مع ان النظام الاصلي بيحسب
![image](https://user-images.githubusercontent.com/71769652/150996778-777cf79d-51c4-4f35-92cd-a8831c8af5fb.png)
![image](https://user-images.githubusercontent.com/71769652/150997124-d0b18efa-09be-4c06-b209-16fed78a9b8f.png)

**Comment by ahmedra2fat** [comment]
جزئية التأكد من الحد الاقصى اشتغلت بس تقريبا بيحسب على الراتب الحالي والمفروض يحسب على الراتب في تاريخ فياريت تراجع عليها وتشوف بيحسب ازاي بالظبط في النظام الاصلي وتطبقه

![image](https://user-images.githubusercontent.com/71769652/158834838-0542c453-ffed-436e-8654-7229b9fe1dc0.png)

![image](https://user-images.githubusercontent.com/71769652/158835082-04491335-9e67-4e7b-bd94-31dbc650780c.png)


الحسبة ظبطت مابين النظامين وبقا النظام الجديد بيحسب نفس القديم بس مع التجارب ظهرت معاية حاله بعينها اختلفت الحسبة في فلس واحد ومعرفش جه منين لان بالتقريب برضو حسبة النظام القديم هي اللي صح فياريت تشيك عليها تاني لان كدة اكيد مع كتر التجارب ممكن يظهر بعض الاختلافات تاني
![image](https://user-images.githubusercontent.com/71769652/158831396-c80c4d8f-e6e8-4f0b-9c16-05f682b6e114.png)

![image](https://user-images.githubusercontent.com/71769652/158831627-3a3d0870-3ca9-4747-874e-6c7380460449.png)


اثناء الاضافة كان نوع الدفع للبنك واثناء الحذف لقيته على نقدي فياريت تظبط دي كمان
![image](https://user-images.githubusercontent.com/71769652/158832787-efc7d041-e369-411b-b8bf-fb87209e791a.png)

![image](https://user-images.githubusercontent.com/71769652/158832885-cb2e6386-c6f0-4dda-8ddc-5effaf20a7d8.png)
