### ISSUE TITLE
frmRepEmpContract.aspx

### ISSUE THREAD

**Issue by MKorain** [TIT-eg/HR#143]
![image](https://user-images.githubusercontent.com/12297634/106946131-645ff200-6731-11eb-917e-5f68a7d8db61.png)
![image](https://user-images.githubusercontent.com/12297634/106946159-6cb82d00-6731-11eb-98f4-dac007f32039.png)
![image](https://user-images.githubusercontent.com/12297634/106946194-78a3ef00-6731-11eb-9e46-7606413f5eaa.png)
![image](https://user-images.githubusercontent.com/12297634/106946205-7d68a300-6731-11eb-9e30-48eadded6a72.png)
![image](https://user-images.githubusercontent.com/12297634/106946237-88bbce80-6731-11eb-9751-ef617a4406a5.png)
![image](https://user-images.githubusercontent.com/12297634/106946257-907b7300-6731-11eb-94e6-476dcf188697.png)
![image](https://user-images.githubusercontent.com/12297634/106946272-96715400-6731-11eb-89a9-0364f8d647cc.png)

**Comment by ahmedra2fat** [comment]
![image](https://user-images.githubusercontent.com/71769652/134879703-ea54298c-b569-4f43-8ed4-54e5b198858d.png)

**Comment by ahmedra2fat** [comment]
دي ماتعملتش وهي ان لما تختار العقود المنتهية حت شهر مع كتابة التواريخ  بيضرب التقرير

![image](https://user-images.githubusercontent.com/71769652/144434044-c7ac7533-d3c5-4b6a-bc60-2ab7af45ac33.png)
![image](https://user-images.githubusercontent.com/71769652/144434080-fc8ce1dc-8045-4929-98a9-848ceb31d31f.png)


وكمان لما تختار الجنسية مع كتابة التواريخ برضو بيضرب التقرير
![image](https://user-images.githubusercontent.com/71769652/144435619-c4b361fd-af78-46d5-a5d0-d6eec40a4483.png)
![image](https://user-images.githubusercontent.com/71769652/144435513-69d0199d-cfde-4fc0-b688-65b6364e998b.png)

**Comment by ahmedra2fat** [comment]
دي ماتعملتش
![image](https://user-images.githubusercontent.com/71769652/158615648-231cd960-5033-4fd4-a560-88d8aa60bb0f.png)

**Comment by ahmedra2fat** [comment]
هي اتعملت بس للاسف ضربت لما بتشيل التشك بتاع الجنسية
![image](https://user-images.githubusercontent.com/71769652/159436885-6f441e12-5e3c-4742-b6f4-4821183041b7.png)

![image](https://user-images.githubusercontent.com/71769652/159436947-c3f8711a-0340-4beb-96d9-1f1c172861ea.png)

**Comment by ahmedra2fat** [comment]
تم
