### ISSUE TITLE
frmPrintEmpDocuments.aspx

### ISSUE THREAD

**Issue by MKorain** [TIT-eg/HR#154]
![image](https://user-images.githubusercontent.com/12297634/107882509-73ddf880-6ef2-11eb-8ee6-3f6584c188f9.png)
![image](https://user-images.githubusercontent.com/12297634/107882514-7c363380-6ef2-11eb-985b-1b76c6d36620.png)
![image](https://user-images.githubusercontent.com/12297634/107882522-848e6e80-6ef2-11eb-9d9a-921071ed0cde.png)

**Comment by Medo20101981** [comment]
![image](https://user-images.githubusercontent.com/71831417/134806389-7acc49b5-ea85-4fe4-befd-a3b17fc0fa3b.png)

**Comment by ahmedra2fat** [comment]
الحاجات دي زي ماهي ماتعملتش

![image](https://user-images.githubusercontent.com/71769652/144431082-0ae1004b-d5b0-458c-8256-dbb09dfc44b8.png)

![image](https://user-images.githubusercontent.com/71769652/144431525-2b8b720c-b831-4277-9853-b8beac25f5c8.png)

**Comment by ahmedra2fat** [comment]
مافيش حاجلة اتعملت
وارفقتلك 4 تقارير بتوع الشاشة كلها غيرهم مكان الموجودينعندك حاليا
وظبط موضوع التاريخ ولازم الرسالة اللي تطلع تبين ايه هو نوع الخطأ يعني في الحالة دي لازم تبين ان التاريخ مكتوب غلط فشوف نص 
الرسالة اللي بتظهر في نفس الحالة من اي شاشة واعمل زيها ومرفق واحده منهم اعملها زيها وخلاص

وبشكل عام اي رسالة خطأ من اي مكان في النظام لازم توضح للمستخدم ايه هو الخطأ لان ماينفعش نقول خطأ في النظام ونسكت

![image](https://user-images.githubusercontent.com/71769652/147950191-0fdc175e-b005-4932-bc5b-46dda3272ecc.png)


![image](https://user-images.githubusercontent.com/71769652/147948002-ea3824cb-0e0a-4d76-844e-a180f0c0a9e9.png)

![image](https://user-images.githubusercontent.com/71769652/147947921-956fd8df-3fa8-462f-8f4f-cf1657917b4b.png)

![image](https://user-images.githubusercontent.com/71769652/147949232-f256d4e6-538c-4d44-ad32-e581537b0777.png)
[EmpDocumentsW.zip](https://github.com/TIT-eg/HR/files/7802719/EmpDocumentsW.zip)
[EmpDocumentsTrack.zip](https://github.com/TIT-eg/HR/files/7802722/EmpDocumentsTrack.zip)
[EmpDocuments.zip](https://github.com/TIT-eg/HR/files/7802723/EmpDocuments.zip)
[EmpDocumentsNArr.zip](https://github.com/TIT-eg/HR/files/7802724/EmpDocumentsNArr.zip)

**Comment by ahmedra2fat** [comment]
تقريبا كل حاجة تمام
بس في مشكلة وهي ان الرسالة دي بتظهر في اي حالة سواء كان التاريخ مكتوب بشكل صحيح او غير صحيح او حتى التاريخ من هو اللي مكتوب بشكل غير صحيح والمفروض ان كل تاريخ منهم يكون له رساله لو التاريخ من اللي خطأ يبقا الرسالة تشير للتاريخ من ولو التاريخ إلى هو اللي خطأ يبقا الرسالة تشير للتاريخ إلى
![image](https://user-images.githubusercontent.com/71769652/150822803-7c15f024-e4ee-48b0-b770-f57d16c4b104.png)

وفي حالة التاريخ من مكتوب خطأ والتاريخ إلى فاضي يبقا تقلي الاول اصحح التاريخ من وبعدين ابقا قلي ادخل التاريخين معا او لاء في حالة اني صححت التاريخ من ومكتبتش التاليخ إلى
![image](https://user-images.githubusercontent.com/71769652/150823172-b4748a25-b1bf-4d2d-a9d4-f2d628b29bb6.png)

**Comment by ahmedra2fat** [comment]
تقريبا زي ماهي ومحصلش عليها تغيير
ياريت تتراجع تاني

**Comment by ahmedra2fat** [comment]
تم
