### ISSUE TITLE
frmQVTicket_Header.aspx

### ISSUE THREAD

**Issue by MKorain** [TIT-eg/HR#155]
![image](https://user-images.githubusercontent.com/12297634/107882597-df27ca80-6ef2-11eb-8773-7596c321f7c9.png)
![image](https://user-images.githubusercontent.com/12297634/107882600-e8b13280-6ef2-11eb-921c-edb8d8eb66c4.png)
![image](https://user-images.githubusercontent.com/12297634/107882616-0bdbe200-6ef3-11eb-8e1d-737d228ecc43.png)

**Comment by Msamy1999** [comment]
تمام جربتها و ظبطها. جرب و لو في مشكلة تانية قول

**Comment by ahmedra2fat** [comment]
بعد ملئ البيانات لا يجب السماح بتعديل حقلي مفرد الراتب و نوع الاجراء
![image](https://user-images.githubusercontent.com/71769652/150809822-31a325e6-deee-4ce3-9fb4-6cdd676fcd91.png)
![image](https://user-images.githubusercontent.com/71769652/150811057-c22e4bcf-d91f-4684-ba89-7b9ad0731119.png)


وكمان كما جاء في النقطة رقم 7 في اول التاسك وخلاصتها انك بلاش تقفل شاشة الدفع بعد اتمام عملية الدفع وخليها قدامي وانا اللي اقفلها بنفسي من زر خروج وطبعا ساعتها تكون كل الوظائف اللي فيها مجمدة يعني ماينفعش اعمل اي حاجة فيها غير حفظ بيانات الجدول والخروج فقط لاغير
وطبعا الملاحظات دي في الوجهتين عربي وانجليزي

**Comment by ahmedra2fat** [comment]
تم
