### ISSUE TITLE
frmTmpEmployeeData.aspx

### ISSUE THREAD

**Issue by MKorain** [TIT-eg/HR#175]
![image](https://user-images.githubusercontent.com/12297634/107883507-18af0480-6ef8-11eb-9374-ed35f624dc73.png)
![image](https://user-images.githubusercontent.com/12297634/107883511-21073f80-6ef8-11eb-974f-2b9fd78803ce.png)
![image](https://user-images.githubusercontent.com/12297634/107883514-282e4d80-6ef8-11eb-9412-22cc955e6964.png)
![image](https://user-images.githubusercontent.com/12297634/107883520-2f555b80-6ef8-11eb-9d15-2104aa35ea9b.png)
![image](https://user-images.githubusercontent.com/12297634/107883531-35e3d300-6ef8-11eb-90bb-6bd152b7c504.png)

**Comment by Msamy1999** [comment]
بيتم استخراج بي دي اف فى زر الطباعة

**Comment by ahmedra2fat** [comment]
اولا التاسك ده منقول من الاجور بشكل عشوائي جدا جدا بمعنى ان تسلسل التعليقات غير مرتب فبكده انا صعب اقدر اركز فيه عشان اقدر اعرف مين قبل مين ومين بعد مين لان الترتيب مهم جدا في التعليقات عشان اقدر اعرف ايه اللي اتعمل وايه اللي ماتعملش لان كل تعليق مكتوب بيستند على التعليق اللي قبله ودي حاجة

الحاجة التانية ان الشاشة دي حاليه مابترجعليش بيانات كل الموظفين في الجدول بمعنى ان في موظفين بترجع بياناتهم في الجدول وموظفين لاء ف على اي اساس ده بيتم الله اعلم والموظف رقم 2 ده واحد منهم على سبيل المثال وليس الحصر 
![image](https://user-images.githubusercontent.com/71769652/147958434-01ffb4f5-d8ca-44f3-a731-ac6e77157d68.png)


الحاجة التالته الكلمات اللي ظاهرة بالنجليزي قي القوائم المنسدلة تترجم ادام احنا في الواجهه العربي
![image](https://user-images.githubusercontent.com/71769652/147958546-41ecbc6f-c73e-4b4a-8d02-92705982f894.png)


الحاجة الرابعة مربعات الاختيار مشلازم اكون واقف بالماوس فوق المربع تحديدا عشان اقدر اختاره خليها ان لو واقف على اي مكان فوق الكلمة نفسها واكلك بالماوس فيعلم في المربع
![image](https://user-images.githubusercontent.com/71769652/147958826-fd23df32-915c-47c9-95f5-89d7d7c3244c.png)


الحاجة الخامسة مسلسل الجدول يكون على مستوى الموظف وليس على مستوى اسطر البيانات عشان في النهاية اقدر اعرف كام موظف رجع بياناته في الجدول
![image](https://user-images.githubusercontent.com/71769652/147959338-e27f7b9f-d878-4ae1-9453-1b089f75bbdc.png)

الحاجة السادسة لما اكون مختار اوبشت التقييم المفروض ان التققيم لاخر ثلاث سنوات يظهرو في سطر واحد وكل سنه في خانه وليس كل سنه في سطر
![image](https://user-images.githubusercontent.com/71769652/147959708-cce51b46-52d5-4be3-92d2-f3a7c222fc99.png)

الحاجة السابعة ياريت في الطباعة او الحفظ تطلع البيانات بنفس اتجاها الموجود بالجدول اللي في الشاشة يعني لو فاتح عربي الجدول بيكون من اليمين للشمال فالبتالي المفروض الطباعة الو الحفظ تطلع نفس الاتجاة
![image](https://user-images.githubusercontent.com/71769652/147960004-8db627de-a9c0-40c5-b31f-61a588cdf470.png)
![image](https://user-images.githubusercontent.com/71769652/147960270-897e16f3-426e-4153-a36c-5a6757c2fc8d.png)
![image](https://user-images.githubusercontent.com/71769652/147960357-348e0e30-8f96-4c3e-85ab-2713189e27fd.png)
![image](https://user-images.githubusercontent.com/71769652/147960431-18d075fe-18d2-47bb-aff7-f16be416539d.png)

**Comment by ahmedra2fat** [comment]
على فكرة لما بقلب النظام انجليزي تقريبا الشاشة مش شغالة ومابترجعش بيانات وصعوبة في كتابة رقم الموظف وفيها عيوب كتير ياريت تتراجع وتبقا زي العربي

اما في العربي
حفظ بيانات الجدول للورد لسه بتطلع من الشمال ياريت تبقا من اليمين ادام فاتح بالعربي وياريت كمان لو امكن صفحات الورد تطلع بالعرض مباشرةً عشان يعرض كل البيانات مش لازم انا بعد ما فتح الورد اقلب الصفح

حاليا الحفظ للاكسل مش غال وبيدي خطأ في النظام وبيطلع بره
![image](https://user-images.githubusercontent.com/71769652/149183495-e7e0b3aa-a269-4367-8783-27b68ec88073.png)

بلاش تظهر كلمة بتاريخ ادام مافيش مؤهل للموظف
![image](https://user-images.githubusercontent.com/71769652/149183870-90312f3f-b805-4af4-a835-b7a2082a9df2.png)


اوبشن يشمل المستقيلين شغال في حالة ملئ البيانات للكل او عند اختيار ادارة او درجة لكلن لو كتبت رقم موظف مستقبل مابيرجعش البيانات
وعلي سبين الميثال موظف 40 و موظف 5000 مستقيلين
![image](https://user-images.githubusercontent.com/71769652/149185073-b00d865a-7f0f-4e71-9cf9-4726732c3323.png)

**Comment by Msamy1999** [comment]
رقم 1 و 3و 4و5 تمام بنسبة لي البينات بتاظهر من الشمال لليمين الحتاة دي  java script محدش فينا شغال بيها فا مش هنعرف نعدلها طلاما الصفحة شغالة تمام ناجلها لبعدين
