### ISSUE TITLE
frmPrintEmpDocuments.aspx

### ISSUE THREAD

**Issue by MKorain** [TIT-eg/HR#179]
![image](https://user-images.githubusercontent.com/12297634/107883741-595b4d80-6ef9-11eb-8fd1-483184c388cc.png)

**Comment by abdelnasser99** [comment]
فين المشكلة؟

**Comment by ahmedra2fat** [comment]
المشكلة موجوده في التاسك 154 وتتحل لما التاسك 154 يتحل فخلاص اعتبر ده لاغي
https://github.com/TIT-eg/HR/issues/154
