### ISSUE TITLE
في الاجراءات الذاتية تتم كتابة pa_creater خطأ

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#305]
1- المفروض يكتب اسم المستخدم 

![image](https://user-images.githubusercontent.com/71831417/123625473-73e2f300-d818-11eb-9c4e-0c4eaaac6b9e.png)

2-  مسافة بين الراتب والقيمة زي النظام القديم

![image](https://user-images.githubusercontent.com/71831417/123626238-4b0f2d80-d819-11eb-9556-8743149d09e1.png)

**Comment by nader545** [comment]
المسافة موجودة بين الكلام و المبلغ
