### ISSUE TITLE
frmTmpAllwoance.aspx

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#309]
بعد الضغط الرجوع من شاشة ادخال قيمة العلاوة يجب الابقاء علي بيانات :

رقم المرجع
تاريخ المرجع
تاريخ الاجراء 
المصدر

![image](https://user-images.githubusercontent.com/71831417/126864928-e00fc1f4-c614-40a9-a0d4-05cf10c868f1.png)

**Comment by ahmedra2fat** [comment]
تم
