### ISSUE TITLE
frmTmpAllwoance.aspx

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#311]
في اجراء العلاوة المجمعة في حالة ادخال علاوة مرة في المرة الثانية لا يطبع ولا ينفذ اجراءات المرة الثانية
![image](https://user-images.githubusercontent.com/71831417/126870273-2dd0293f-0a7c-426b-9343-4cf04a1a2df9.png)

**Comment by abdelnasser99** [comment]
@Medo20101981 برجاء التوضيح هنا

**Comment by Medo20101981** [comment]
النظام مصمم انك ممكن تعمل اجراء علاوة مجمع أكتر من مره في السنة
المشكلة ان النظام بيشتغل صح أول مرة بس 
تاني مرة بيطلع الرسالة دي 
"تحذير - لقد تم ادخال علاوات بالفعل لنفس السنه فى ملف الاجراءات الذاتيه هل ترغب فى الاستمرار ؟"
ولما بتعمل نعم المفروض النظام يكمل ويحضر علاوات للناس اللي مخدتش قبل كده بس
لكن للأسف مبيعملش حاجة
اعتقد المشكلة في ال Validation 

لو لسه الامور مش واضحة كلمني واتس اب او ديو او تلجرام علي الرقم ده 0096567003031
علشان ننجز أسرع
