### ISSUE TITLE
rmTmpEmployeeSal.aspx

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#315]
صفحة رواتب الموظفين حتى تاريخ ومخصص نهاية الخدمة
تقرير مخصص نهاية الخدمة لفترة لا يعمل

![image](https://user-images.githubusercontent.com/71831417/126893648-24f1c5e4-45f6-44ef-bab4-e84c4db08697.png)

EmpServiceEndEQPeriod.rpt

**Comment by Medo20101981** [comment]
التقرير بيطبع في الماضي لكن بيطبع فاضي في المستقبل
![image](https://user-images.githubusercontent.com/71831417/134811351-4b4430fb-3d8b-493d-9c4c-0fd5eb844151.png)

**Comment by Medo20101981** [comment]
خد التقرير ده واعملة مكانة علشان يطلع الأرقام ص
[EmpServiceEndEQPeriod.zip](https://github.com/TIT-eg/HR/files/7808445/EmpServiceEndEQPeriod.zip)
ح

**Comment by Msamy1999** [comment]
تمام جرب كده

**Comment by Medo20101981** [comment]
التقرير لسه زي ما هو 
![image](https://user-images.githubusercontent.com/71831417/148362033-caab0567-7eb8-4682-b8e8-b8f2aa77d713.png)

**Comment by Msamy1999** [comment]
طب كدا طب
