### ISSUE TITLE
frmIndustrial_ActionsAdd.aspx

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#320]
صفحة العقوبات
1- لا يمكن كتابة رقم الموظف
2- في حالة عدم كتابة عدد أيام الحرمان وكتابة عدد أيام العقوبة النظام يعطي Error
3- قيمة الخصم تحسب خطأ
4- كلمة المرور المفروض تكون فارقة
5- تعديل الرسالة الي تاريخ التنفيذ يجب ان يكون اكبر من او يساوى من تاريخ العقوبة
"الرسالة دي موجودة في النظام القديم برضة وهنعدلها ان شاء الله"
![image](https://user-images.githubusercontent.com/71831417/126897333-65c203b1-5bf8-4984-acbe-9537a8a29f6a.png)

**Comment by Medo20101981** [comment]
1-  عند التعديل علي عقوبة يجب ملء نوع العقوبة  
2- عند كتابة الرقم السري خطأ كلمة موافق بتقف المفروض تسيب المستخدم يدخل كلمة سر تانية
3- شهر الرواتب في الرسالة بدون وقت

![image](https://user-images.githubusercontent.com/71831417/148391067-3802ee3c-cf23-4a36-89fa-c3668d6aa278.png)

![image](https://user-images.githubusercontent.com/71831417/148391117-3c2bbcd1-51e2-4b9a-94c6-c3e91719430f.png)


![image](https://user-images.githubusercontent.com/71831417/148390548-20ef8f75-c249-4286-8039-b463580c15d3.png)

**Comment by Medo20101981** [comment]
![image](https://user-images.githubusercontent.com/71831417/148392270-c7bfc071-ade2-45aa-a0f5-f73df90835d4.png)

لو سمحت كمان الرتب عند تاريخ العقوبة قربه لأخر 3 كسور فقط

**Comment by Msamy1999** [comment]
رقم 1 و 2 مضبطين عندي الباقي عماته جرب تاني و شوف

**Comment by Medo20101981** [comment]
1- عند ادخال عقوبة جديدة يختار المستخدم حقل عقوبة او تأخير 
في التعديل او التفاصيل النظام مش بيملاها والمشكلة دي موجودة في النظام القديم كمان وهتتحل ان شاء الله فممكن تسيبوها دلوقتي 
![image](https://user-images.githubusercontent.com/71831417/149324516-77a937e5-3800-43dd-8d89-de717ddeb870.png)
2- المشكلة التانية هي ان نظام العقوبات بيكتب بيانات في قاعدة البيانات في حالة التعديل بيسيب user3 فاضي
هتلاقي الشرح في ملف الاكسل ده
3- في حالة الدخول للصفحة من خلال تفاصيل لازم يظهر باتون الطباعة
![image](https://user-images.githubusercontent.com/71831417/149330565-13f7a646-0ebb-46f0-922a-f74d412cec51.png)


4- عند عمل تعديل عقوبة والضغط علي تقرير بيطلع تقرير مختلف المفروض يظهر تقرير تعديل عقوبة
![image](https://user-images.githubusercontent.com/71831417/149330708-c9ff89f3-60f1-41b3-87c4-7af83b6342ea.png)

**Comment by Msamy1999** [comment]
3- التقرير المبعوت هو نفس المعروض
