### ISSUE TITLE
frmSpecialUpdate.aspx

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#329]
العلاوة السنوية مبتشتغلش في حالة وجود كسور
![image](https://user-images.githubusercontent.com/71831417/132261795-b70f2c91-285b-4434-b88a-32d090478a91.png)

**Comment by HassanAagwa** [comment]
@Medo20101981  برجاء توضيع المشكله

**Comment by Msamy1999** [comment]
جربت نفس الحالة و شغالة تمام جرب تاني

**Comment by Medo20101981** [comment]
لما بيكون فيه كسور في العلاوة السنوية النظام مش بيحضر الاجراء أصلا

**Comment by Medo20101981** [comment]
اللي عنده التاسك ده لو سمحت يتواصل معايا ويدخل معايا بالزووم  5 دقايق علشان يشوف بنفسه أسرع من الكتابة

**Comment by Medo20101981** [comment]
#328

**Comment by Msamy1999** [comment]
كنت في انتظار التاكيد انها اشتغلتز بس محمد مردش لسا و الداتا عندي بايظة مش عارف اجربز لو فيها مشكلة لسا يرجى التواصلز
