### ISSUE TITLE
frmQVEmployeeLeave.aspx

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#331]
شاشة اجازات الموظفين مبتعرضش بيانات 
ده حصل بعد تحديث النظام القديم
كمان لما تدخل علي شئون الموظفين الداشبورد بتدي ايرور
![image](https://user-images.githubusercontent.com/71831417/134813291-928c7006-ecf9-4432-bf41-f90a219ac632.png)

**Comment by MKorain** [comment]
@Medo20101981 
Please send me the log file after opening this page to track error.
this error is not shown to me.
also please attach last database backup

**Comment by Medo20101981** [comment]
Hi Mohamed
attached is the log file.
the page doesn't display any data
and when I select another module it gave me those errors:

![image](https://user-images.githubusercontent.com/71831417/135434563-11e83881-50ef-4623-bac1-8e44ab2bf4ba.png)


![image](https://user-images.githubuserc
[2021-09-30.zip](https://github.com/TIT-eg/HR/files/7258673/2021-09-30.zip)
ontent.com/71831417/135430957-7fc1789a-9556-4d9b-895b-3db6bf000252.png)
