### ISSUE TITLE
frmMonthEnd.aspx

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#355]
المشكلة في 
SalaryObj.DLL
لأنة المسؤول عن احتساب مخصص نهاية الخدمة

1. في اختيار في نوع العقد معناه خصم قيمة التأمينات الاجتماعية من المكافأة  ده للأسف مش شغال في الويب
[Web.pdf](https://github.com/TIT-eg/HR/files/7833279/Web.pdf)
[Windows.pdf](https://github.com/TIT-eg/HR/files/7833280/Windows.pdf)

2. حقل OrgIndm بيقرب بشكل مختلف عن النظام الويندوز

![image](https://user-images.githubusercontent.com/71831417/148646009-a53d18ca-01b0-4d29-932e-6d2167f7dadd.png)

**Comment by Medo20101981** [comment]
![image](https://user-images.githubusercontent.com/71831417/149202967-dfdd5b14-63e3-492f-a811-a13a514e58ff.png)

**Comment by Msamy1999** [comment]
#127
