### ISSUE TITLE
frmqvemployee.aspx

### ISSUE THREAD

**Issue by ahmedra2fat** [TIT-eg/HR#363]
في شاشة صيانة اجراءات الموظفين الذاتية
التنبيهات اللي بتظهر عند دخول الشاشة كانت شغاله وزي الفل 
وهو انك تدوس على انتر اكنك اختر لا وتختفي الرسالة وتيجي اللي بعدها وهكذا واللي بتحتاج تشوف محتواها بتدوس على نعم بالموس

دلوقتي للأسف خربت وبقت انتر مابتعملش حاجة ولو دوست على انتر اكتر من مرة او دوست بالموس على لا اكتر من مرة وبعدين دوست على نعم بيفتحلك محتوى الرسالة بس ساعتها الصفحة بتهنج حتى الاكس اللي ممكن تقفل منها الرسالة مش شغالة

![image](https://user-images.githubusercontent.com/71769652/149195241-c19f2f74-6ec9-4643-9539-51f020691af4.png)

**Comment by Msamy1999** [comment]
@abdelnasser99

**Comment by ahmedra2fat** [comment]
تم
