### ISSUE TITLE
Dashboard Error - شؤون الموظفين

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#395]
المشكلة بتظهر لو سنة الاجازات في النظام أقل منالسنة الحالية
تقريبا الكود معمول انه بيبجث عن اجازات السنة الحالية  بناء علي تاريخ الكمبيوتر
المفروض ياخد السنة من قاعدة البيانات
select leave_year from control

![image](https://user-images.githubusercontent.com/71831417/156571987-eac699ee-d1ef-4dde-ae2d-b1b39a811d76.png)

**Comment by Msamy1999** [comment]
جرب كدا
