### ISSUE TITLE
بعض المشاكل عند التركيب عند عميل جديد

### ISSUE THREAD

**Issue by ahmedra2fat** [TIT-eg/HR#414]
عند الدخول على موديول المرتبات يعطي هذه الرسالة على الداش بورد
![image](https://user-images.githubusercontent.com/71769652/162633546-c76d600d-9f9d-418c-8f2c-28f15a304bc0.png)

في داش بورد موديول بيانات الموظف الأساسية يكون تاب عدد الموظفين 0 في حين ان موديول شئون الموظفين يقرأ العدد صحيح
![image](https://user-images.githubusercontent.com/71769652/162633672-d80b5150-3a2f-4098-bd03-17471e44bcab.png)

وبعد عرض بيانات التاب عدد الوظفين يسترجع بيانات صحيحة ولكن بعد اغلاقة يتم تفريغ تابات الداش بور من العداد
![image](https://user-images.githubusercontent.com/71769652/162633710-37957573-bce7-47d1-affe-5a695bcb7867.png)
![image](https://user-images.githubusercontent.com/71769652/162633728-7e436588-f17d-4740-888c-4962d4535639.png)

عند اضافة موظف جديد بتاريخ تعيين اقل من شهر المرتبات الحالي يقبل اضافة الموظف ولكن يعطي خطأ عند احتساب الاثر الرجعي للراتب ولا يسجلة في شاشة الاضافات والخصومات كتسوية بالاثر الرجعي في حين انها شغاله في النظام الاصلي
![image](https://user-images.githubusercontent.com/71769652/162634221-2cbec9e9-3f07-4e9b-ad8d-abc33be0132e.png)
![image](https://user-images.githubusercontent.com/71769652/162634244-b755f11c-e6bc-417e-823f-d4ccd43b74df.png)
![image](https://user-images.githubusercontent.com/71769652/162634322-104d03a6-0968-4f39-8282-b48cc4586efe.png)

شاشة تقارير الموظفين وشاشة تقارير رواتب الموظفين اللي في موديول شئون الموظفين وموديول بيانات الموظف الاساسية بيظهر فيهم عربي مشفر وفي بعض التقارير بتدي ايرور
دي امثلة على سبيل المثال وليس الحصر ولذلك مطلوب مراجعة وتشييك على كل التقارير الموجودة بالشاشتين
![image](https://user-images.githubusercontent.com/71769652/162635633-7cbd3dc0-fcc8-4cb8-91cc-f494a36c95bd.png)

![image](https://user-images.githubusercontent.com/71769652/162635371-fe8c86b8-4001-47f1-bbc8-f686c14a82ec.png)
![image](https://user-images.githubusercontent.com/71769652/162635401-1a51a717-0251-44cf-871a-1c0324e62c09.png)
![image](https://user-images.githubusercontent.com/71769652/162635427-a85c61c8-4061-4989-9bd8-d4818ce2b08d.png)
![image](https://user-images.githubusercontent.com/71769652/162635488-a266a785-037a-4224-b3aa-bcd16375e121.png)
![image](https://user-images.githubusercontent.com/71769652/162635512-543d247b-fb86-4cfa-949e-ff70b25867b6.png)

شاشة طباعة الارصدة المستحقة حتى تاريخ
للاسف تقرير الشاشة دي مابيحسبش الارصدة حتى تاريخ وعشان يطلع نتائج صحيحة لازم اروح اشغل التقرير من النظام الاصلي الاول وبعدين اطبعة من الويب يعني تقرير الويب بيقرأ المحسوب من قبل فقط ولا يحسب جديد
![image](https://user-images.githubusercontent.com/71769652/162636013-8d41e00a-176e-4618-bfca-088cae8db818.png)
التقرير ده لما طبعت من الويب الاول مع العلم ان الاتنين الموظفين المحسوبلهم دول ماكنوش بيظهرو غير لما طبعته من النظام الاصلي وعشان اتأكد روحت رصت للموظف رقم 1 وجربط اكبع من الويب اداني النتيجة صفر وبعد ما طبعت من النظام الاصلي تاني ورجعت طبعت من الويب جاب النتيجة
![image](https://user-images.githubusercontent.com/71769652/162635993-ba4b33a0-e9a3-4c23-9388-62b3d5226273.png)
![image](https://user-images.githubusercontent.com/71769652/162636048-fb6542e1-5ca3-4be6-aaa6-601b27cf4000.png)

وللاسف في مشاكل كتيييييير بس كفاية كده عل التاسك ده

**Comment by Msamy1999** [comment]
تم انتهاء من مشكلة الداش بورد كاملة

**Comment by ahmedra2fat** [comment]
ملاحظات على الحاجات اللي خلصت

تاب تنبيهات الوثائق مابيعرضش البيانات
![image](https://user-images.githubusercontent.com/71769652/162830549-cebbb887-2d4a-4405-945c-65e9b0ae333d.png)

وبالنسبة للتقارير اللي في شاشاتين تقارير الموظفين وتقارير رواتب الموظفين معظمها اتظبط بس تقريبا كلهم مابيعرضوش تاريخ التعيين يمكن تقرير واحد بس هو اللي عارض تاريخ التعيين وهو تقرير مؤهلات الموضفين اما باقي التقارير مابتعرضوش
وتقرير مرتب على حسب الادارة لسه فيه عربي مشفر
وتقرير الراتب مجمع بردو عربي مشفر
وتقرير مفصل للموظف مابيطبعش
وتقرير مرتب على حسب الادارة مع الراتب لسه فيه عربي مشفر
وتقرير - مجمع-قطاع -إدارة مابيطبعش وكمان هو اصلا مش موجود في النظام الاصلي فياريت تشيك عليه تشوفه جاي منين او وضعه ايه
وتقرير الراتب - مفصل - مع الخصومات بيضرب
وتقرير الراتب - مفصل - رأسى بيضرب

**Comment by ahmedra2fat** [comment]
في موضوع اضافة موظف جديد واحتساب الاثر الرجعي هو النظام سجل الاثر الرجعي بتاع الراتب ولكن مادنيش اي رسالة زي الاول ويخيرني بأضافة الاثر الرجعي ولا لاء. لازم تظهر الرسالة في حالة كان تاريخ التعيين اقل من شهر المرتبات الحالي وانا ساعتها اختار من احتساب الاثر الرجعي او لاء
![image](https://user-images.githubusercontent.com/71769652/163143538-803e9537-d6de-4988-9f1b-4c3130a17489.png)

في حالة اختيار بدل للطباعة مع هذا التقرير بيضرب
![image](https://user-images.githubusercontent.com/71769652/163146489-62e9485e-77ea-4d33-9790-e85aba21d37a.png)
![image](https://user-images.githubusercontent.com/71769652/163146583-4e62ef15-2597-4325-9f21-494dce11baa3.png)

**Comment by Knk11** [comment]
حل المشاكل
