### ISSUE TITLE
بعض المشاكل عند التركيب عند عميل جديد - 2

### ISSUE THREAD

**Issue by ahmedra2fat** [TIT-eg/HR#415]
frmEmployeeBankAdd.aspx
في شاشة بنوك الموظفين
عند اضافة البيانات البنكية لموظف يجب طباعة تقرير بها كما بالنظام الاصلي
![image](https://user-images.githubusercontent.com/71769652/162636809-fc5ca9e7-6f08-4114-be8c-d7d3c4084c0a.png)

عند عرض تفاصيل او تعديل على البيانات البنكية لبعض الموظفين لا يتم استرجاع رقم الموظف ولا الاسم ولا الادارة
![image](https://user-images.githubusercontent.com/71769652/162637053-fc7e54ab-6d89-4c3d-a17d-d75ca4c98aec.png)

frmemppaq.aspx
في شاشة صيانة اجارات الموظفين الذاتية وعند اضافة اجراء لموظف ليس له راتب لا يسترجع بعض بيانات الموظف وعند الاستكمال لاضافة اجراء يعطي خطأ بينما في النظام الاصلي في نفس الحالة يعطي رسالة توضح ان الموظف ليس له راتب
![image](https://user-images.githubusercontent.com/71769652/162637812-257b06d4-4441-4961-92cb-bdeff75434a2.png)
![image](https://user-images.githubusercontent.com/71769652/162637824-e590f833-0c14-465e-a565-46d6204f18de.png)
![image](https://user-images.githubusercontent.com/71769652/162637853-9483f18c-e443-4c57-81d6-17b52d0bdf48.png)
![image](https://user-images.githubusercontent.com/71769652/162637896-64fc815c-66af-45ca-ac00-af17c03284ae.png)

عند الدخول على موديول وثائق الموظفين يعطي هذه الرسالة
![image](https://user-images.githubusercontent.com/71769652/162638133-90af93d5-b0b9-4e6e-aa98-f3ea08bb9247.png)

في موديول شئون الموظفين وموديول بيانات الموظف الاساسية
عند وجود تنبية بالوثائق التى في فترة التنبية وطباعة التقرير يطبع وثائق الموظف فقط ولا يطبع وثائق الشركة في حين ان النظام الاصلي يطبع الاثنين
![image](https://user-images.githubusercontent.com/71769652/162638572-163d34ae-84b0-43b6-8767-b00e61db35ce.png)
![image](https://user-images.githubusercontent.com/71769652/162638587-6d813d88-ec6b-42f3-88aa-4c096aa5f979.png)

وفي مشكلة في الاجازات ان بيدي خطأ عند الموظفين المنقول بياناتهم من خلال قاعدة البيانات فبالتأكيد القصور حيكون في البيانات نفسها لان لما بدخل موظف جديد من خلال النظام بتشتغل كويس بس المشكلة ان الخطأ اللي بيطلع عن الموظفين المنقول بيانتهم دول مابيطلعش في النظام الاصلي وشغاله كويس فا من المفترض ان ادام شغاله من النظام الاصلي يبقا المفروض تكون شغاله من النظام الجديد
والمشكلة بتظهر احيانا عند اضافة اجازة واحيانا عند عرض تفاصيل او تعديل على اجازة فا اعتقد الموضوع ده محتاج حد يدخل معاية ويجربها عندي

**Comment by Msamy1999** [comment]
عند اضافة البيانات البنكية لموظف لا يوجد طباعة في السيستم القديم

**Comment by Msamy1999** [comment]
عند عرض تفاصيل او تعديل على البيانات البنكية لبعض الموظفين لا يتم استرجاع رقم الموظف ولا الاسم ولا الادارة

بيتم استرجع عندي برجاء توضيح بامثلة

**Comment by Msamy1999** [comment]
عند الدخول على موديول وثائق الموظفين يعطي هذه الرسالة

خلص

**Comment by ahmedra2fat** [comment]
ملاحظات على الحاجات اللي خلصت

بخصوص طباعة تقرير البيانات البنكية عند الاضافة
هي اتعملت وفعلا بقا بيظهر زر التقرير وبيطبع بس البيانات اللي بالاسود دي المفروض ماتظهرش غير في حالة كنت بعدل بيانات البنك للموظف وبالتالي بيجبلي فيها بيانات البنك ورقم الحساب اللي قبل التعديل
اما في حالة الاضافة يجب اخفائها
![image](https://user-images.githubusercontent.com/71769652/162839744-ef5b8a2f-ec00-4c28-ae7a-edae4276bc8d.png)

في ملاحظة كمان اكتشفتها اثناء الغاء بيانات بنك لموظف
اولا: النظام بيفتح في صفحة تانية خارجية وده غلط مش المفروض يحصل كده والمفروض انه يظل على نفس الصفحة اللي انا شغال عليها
ثانيا: بعد اتمام عملية الالغاء وظهور رسالة تم الحذف بنجاح يجب تجميد زر موافق وطباعة والابقاء فقط على زر خروج للتمكن من الرجوع لشاشة بنوك الموظفين
![image](https://user-images.githubusercontent.com/71769652/162841162-4a354bce-2006-437f-a042-d2b981ad916e.png)

![image](https://user-images.githubusercontent.com/71769652/162840847-ea825321-b597-4531-9c36-5d2d784a7b2f.png)


في داش بورد وثائق الموظفين تاب تنبيهات الوثائق وتاب تنبيهات جواز السفر لا يعرضو بيانات
![image](https://user-images.githubusercontent.com/71769652/162841832-65754c9a-53ef-4c7c-82ed-b877bb4d884c.png)

**Comment by Msamy1999** [comment]
محتاج توضيح لدي كله خلص

**Comment by ahmedra2fat** [comment]
توضيح اكتر من كده في موضوع الاجازات يبقا تدخل معاية وتشوف على الطبيعة


يجب تفعيل الطباعة عند تعديل بيانات البنك لموظف
![image](https://user-images.githubusercontent.com/71769652/163130222-6f2ae5a6-e10f-4a38-8309-e30b8779d133.png)
![image](https://user-images.githubusercontent.com/71769652/163130940-222fa48f-07dc-4d1e-829d-8332e077a27a.png)


عند فتح شاشة وثائق الموظفين يجب اظهار جميع الوثائق الاكتف في الشاشة مع الاختيار نعم وهي كانت كدة الاول دلوقتي لازم اختار لا عشان تظهر ولو خرجت من الشاشة ودخلا تاني بترجع تختفي تاني فياريت تظل الوثائق الاكتف ظاهرة في الشاشة مع الاختيار نعم ولما اختار لا يظهر معاهم الان اكتف
![image](https://user-images.githubusercontent.com/71769652/163134023-30641a44-3e75-4419-bee0-a6228d3a4013.png)


في موديول شئون الموظفين وموديول بيانات الموظف الاساسية شاشة بيانات الموظفين الاساسة
عند وجود تنبية بالوثائق التى في فترة التنبية وطباعة التقرير يطبع وثائق الموظف فقط ولا يطبع وثائق الشركة دي في موديول شئون الموظفين يعني زي ماهي محصلش فيها حاجة
![image](https://user-images.githubusercontent.com/71769652/163138516-440a6887-a110-44ea-88a5-bc3d0b20896f.png)
![image](https://user-images.githubusercontent.com/71769652/163138841-89b127f0-f332-4593-99b2-63163652c256.png)

اما في موديول بيانات الموظف الاساسية حاليا بقا بيطبع كل الوثائق الموجودة بغض النظر عن فترة التنبية
![image](https://user-images.githubusercontent.com/71769652/163139222-9fdda34c-fced-4e2a-9cf4-f58627264973.png)
![image](https://user-images.githubusercontent.com/71769652/163139332-92a179ce-61c1-4cd5-ad51-3dcd7e748780.png)


تاب تنبيهات الاقامة لا يعرض بيانات
![image](https://user-images.githubusercontent.com/71769652/163140274-9bae68c5-baba-4079-8a70-06e0a1200573.png)

**Comment by ahmedra2fat** [comment]
دي ماتعملتش
![image](https://user-images.githubusercontent.com/71769652/163337148-9d2eed3e-7fa6-4815-8c72-0d5e52d3ba4d.png)

**Comment by Msamy1999** [comment]
هيا مش ظاهرة عندي فجرب المفروض كدا تمام جرب و لو لسا قولي

**Comment by ahmedra2fat** [comment]
لسه زي ماهي

**Comment by ahmedra2fat** [comment]
تم
