### ISSUE TITLE
frmImportDedAdd.aspx

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#66]
Please add the Import Button and the screen

**Comment by ahmedra2fat** [comment]
خانة الاجمالي ماينفعش يتكتب فيها 
![image](https://user-images.githubusercontent.com/71769652/163716871-2ffe9f2a-2487-4afd-a217-f57567d3ce7d.png)

في حال كان في رقم موظف خطأ في ملف الاكسل النظام بيقف عنده ومابيكملش بينما في النظام الاصلي بيكمل الملف كامل ولكن بيوضح ان في اخطاء في البيانات المدخلة
![image](https://user-images.githubusercontent.com/71769652/163717453-ad9a9301-a3a5-4047-ae9e-ed581e207608.png)
