### ISSUE TITLE
frmQVContracts_Under.aspx

### ISSUE THREAD

**Issue by MKorain** [TIT-eg/HR#7]
شاشة العقود تحت التحضير بها التعديل لا يعمل
![image](https://user-images.githubusercontent.com/12297634/94009472-cb919100-fda4-11ea-8e22-ccd609235da8.png)

**Comment by ahmedra2fat** [comment]
على سبيل المثال وليس الحصر لذا يرجى مراجعة الشاشة بعناية ومطابقتها بالنظام الاصلي

الالتزام بنفس الحقول المتاحة للتعديل بالنظام الاصلي
![image](https://user-images.githubusercontent.com/71769652/158630961-d8b5da6c-1124-4760-813d-6597baf47568.png)

خانة رقم الموظف تسترجع بيان خطأ
![image](https://user-images.githubusercontent.com/71769652/158631297-43a0f006-c32c-41b8-b1d5-c1713502b0c0.png)
