### ISSUE TITLE
frmQVEmployee_loans.aspx

### ISSUE THREAD

**Issue by Medo20101981** [TIT-eg/HR#85]
مطلوب امكانية التحكم في عرض السجلات النشطة فقط في الجدول

ممكن نعمل راديو باتون فوق الجدول يكون فيه الاختيار بين:
 (جميع السجلات / النشط فقط)
بالانجليزي 
(Show active records only/ Show All)

![image](https://user-images.githubusercontent.com/71831417/102087289-5f19b180-3e2a-11eb-83cb-2889a2af1fdf.png)

**Comment by Msamy1999** [comment]
<img width="595" alt="Screenshot_38" src="https://user-images.githubusercontent.com/90830374/147777914-8ecb30c9-214d-45c8-9ed6-85015487ee76.png">

**Comment by Msamy1999** [comment]
مش هينفع لا دا grid view  بيتبعت على بعضه ك fun() مش front

**Comment by ahmedra2fat** [comment]
@Medo20101981

**Comment by Medo20101981** [comment]
لو سمحتم خلو الكلام في سطر واحد زي ما أحمد وضح في الصورة
![image](https://user-images.githubusercontent.com/71831417/148074215-0c157432-f6dd-438d-913c-69ca049d24d3.png)

**Comment by Msamy1999** [comment]
تمام جرب كده

**Comment by Medo20101981** [comment]
لو سمحت قبل ما تعدل علي التاسك اعمل انت تيست الأول 
للأسف الشكل تمام بس مبيقبلش تغير الراديو باتون
